### PR TITLE
feat!: convert to es modules, drop node 10

### PR DESCRIPTION
**Pull request by JustinBeckwith**
BREAKING CHANGE: this module now requires node.js 12 and above, and has moved to es modules by default.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@bcoe this is super weird.  Looks like everything works in node 14 and 16, but only on 12 I am getting:  
```
> c8 mocha build/test


SyntaxError[ @/home/runner/work/linkinator/linkinator/build/test/test.cli.js ]: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```

I have no idea how to further debug this since I'm getting no stack trace 🤔   Ideas on who to ask here?

**Comment by JustinBeckwith** [comment]
Ok, well that was terrible to figure out.  Regardless :) @bcoe could I trouble you for a code review on this one?  There are a lot of changes in the ES Modules realm, and I would love a second set of eyes.

**Comment by bcoe** [comment]
@JustinBeckwith happy to look 👍

**Comment by bcoe** [comment]
I'm late to the game, but these changes look right to me.

**Pull request merged**
