### PR TITLE
feat: Add port option to CLI

### PR DESCRIPTION
**Pull request by Noah-Silvera**
Added an option to set the port for the web server used for local scans to the CLI

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the PR!  I'm curious - what's the situation where this would be needed?  Generally the temporary web server that gets stood up is just for the duration for the scan, so the specific port shouldn't matter.  For cases where you're running your own web server, you can specify a host instead of a filesystem path.  Just trying to make sure I understand the situation where this is helpful :)

**Comment by Noah-Silvera** [comment]
> Greetings, and thanks for the PR! I'm curious - what's the situation where this would be needed? Generally the temporary web server that gets stood up is just for the duration for the scan, so the specific port shouldn't matter. For cases where you're running your own web server, you can specify a host instead of a filesystem path. Just trying to make sure I understand the situation where this is helpful :)

Hey Justin! 
Great question. I am attempting to use the linkinator in our CI system to check links on a prod build of documentation before merge. However, the prod build of the documentation has hardcoded links to the prod environment, i.e. https://<prod-website>/some-docs-file.html

The issue occurs when the hardcoded links to the prod environment reference documentation files which have been newly added and don't yet exist in the prod environment. 

For example, if the PR adds a documentation file, "tutorial-create-a-component", then the CI build will generate output with hardcoded links to https://<prod-website>/tutorial-create-a-component. These links are broken, as the "tutorial-create-a-component" file has never been deployed to prod, and will continue to be broken until it is deployed to prod.

However, if we tell the CI build that the <prod-website> **is the webserver that linkinator runs**, then the links to files which haven't been deployed to the <prod-website> will be valid, as they will exist on the linkinator server.

**Comment by JustinBeckwith** [comment]
Thanks for explaining!  The issue is, I don't think this particular fix will get you what you want :) When you invoke linkinator, are you pointing it at an http endpoint to scan, or are you pointing it at the local file system?  

I *think* what you're saying is, you generate documentation pages with hard coded URLs which at the time of CI running, do not exist.  Is that correct?

**Comment by Noah-Silvera** [comment]
> Thanks for explaining! The issue is, I don't think this particular fix will get you what you want :) When you invoke linkinator, are you pointing it at an http endpoint to scan, or are you pointing it at the local file system?


We are pointing it at the local file system.

This is the steps we would use to integrate linkinator into our CI

- Set an env variable to `http://localhost:<linkinator-port>`
- Use the env variable in our build configuration, so that the documentation has hardcoded URLs that point to `http://localhost:<linkinator-port>/some-docs-page`
- Run the build
- Run linkinator on the local build output. Since the hardcoded URLs are pointing to linkinators server ,they will be valid.

> I _think_ what you're saying is, you generate documentation pages with hard coded URLs which at the time of CI running, do not exist. Is that correct?

This is correct! The build configuration requires a base URL (the url of our prod site) to be set in config order for certain hard coded links to be generated. These hard coded links fail until the website is actually deployed

**Comment by Noah-Silvera** [comment]
Hey @JustinBeckwith! Just wanted to check in and ask if there was anything else you needed from me for this PR. Thanks!!

**Comment by JustinBeckwith** [comment]
Apologies for the delay here - too much time on work OSS and not enough on personal OSS 😆  I'm trying really hard to keep the surface for the CLI and config small here, so forgive me for being a little rigid.  Thinking out loud - I suspect you could accomplish the same thing without a new flag!  Really all I'm doing here is bootstrapping a simple static web server under the hood, and I think you could do the same, right?

```
$ npx http-server . -p 3000
```

Then, run `linkinator` against that url instead of the local filesystem path:
```
$ npx linkinator http://localhost:3000
```

Would that get you where you want to go?

**Pull request closed without merging**
