### PR TITLE
test: unlink the package after tests are done

### PR DESCRIPTION
**Pull request by XhmikosR**
Refs #245.

I still think it's worth dropping the whole link/unlink thing, but I'll leave this to you @JustinBeckwith :)

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
I have no idea what's going on with these test flakes, but they never reproduce locally 🤯

**Review by JustinBeckwith — APPROVED** [review]

**Comment by JustinBeckwith** [comment]
A few other thoughts:
- Since this has no material impact on the code shipped, we should use the `test: ` conventional commits prefix.  That way `semantic-release` won't try to ship a new release once this lands
- On dropping `link` entirely - I am trying to make sure we actually test the CLI like a user would use it.  The only other thing I could think to do was to run `node build/src/cli.js` as part of the tests, but that isn't exactly the same as user invoking `linkinator`.  There's a lot I don't know here, so if you know of other CLI testing patterns around, I'd love to hear it!

**Comment by XhmikosR** [comment]
@JustinBeckwith I'm not familiar with conventional commits hence why my commit messages don't follow that. Feel free to adapt while merging, thanks!

**Comment by XhmikosR** [comment]
I'd say the best would be if you didn't use `npm link/unlink` at all. It affects the system tests run on, at least it's what I notice on my Windows VM. And as a plus, tests would be sped up.

**Comment by JustinBeckwith** [comment]
I think we're good here with the changes in #251

**Pull request closed without merging**
