### PR TITLE
fix: use custom HTTP server

### LINKED ISSUE #233: Investigate failures in twbs/bootstrap
Starting with recentish release, linkinator started failing on a perfectly valid link in the bootstrap docs.  The issue was raised here:
https://github.com/twbs/bootstrap/pull/32678#issuecomment-754671269

This link shows a 404:
https://getbootstrap.com/docs/5.0/

I debugged a little and it turns out to be an issue with the https://github.com/vercel/serve-handler transition, which was done for directory listings.  More research needed. 

cc @XhmikosR

### PR DESCRIPTION
**Pull request by JustinBeckwith**
Not quite ready for primetime yet.  Fixes #233.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@XhmikosR this is handling everything I've tested it with, including bootstrap. Could I trouble you to give this a shot, and make sure everything looks right?  It's a bit of a scary change 😆

**Comment by XhmikosR** [comment]
I checked out the branch, built it and replaced the local linkinator I had and it seems to work. Nice job!

It feels like reinventing the wheel as long as it works fine :)

PS.

1. still getting some failures on my Windows VM like on CI
2. do you plan to switch to async/await for fs methods in server?
3. I would suggest adding a test with a folder with periods

**Comment by JustinBeckwith** [comment]
Sweet.  Looking at these:

> still getting some failures on my Windows VM like on CI

Yeah I ran these on my windows machine, and the CLI tests just randomly will take 5 seconds to spawn a process.  I have no idea what to do here, but I don't think this is new.  

> do you plan to switch to async/await for fs methods in server?

Done in the latest build

> I would suggest adding a test with a folder with periods

lol good call, done

> should there be some kind of caching?

So I thought about this, and no!  The crawler caches all responses once it visits a url, so there's no way that you would need to load the same file twice.  The cache would never actually get used - one of the many things in a normal static web server that I think it's easy to leave out here, because the only client for these requests will ever be gaxios/linkinator

**Comment by XhmikosR** [comment]
> So I thought about this, and no! The crawler caches all responses once it visits a url, so there's no way that you would need to load the same file twice. The cache would never actually get used - one of the many things in a normal static web server that I think it's easy to leave out here, because the only client for these requests will ever be gaxios/linkinator

Yeah, I wasn't sure if it was needed either, just thought I'd mention it :)

One last thing, it seems this PR introduces a few further CodeQL issues. Not sure if all apply since I don't see all the details yet (when LGTM runs, I should be able to see them, but I don't have access to the security tab). One of them should be easy to fix by escaping any characters like you do elsewhere.

**Pull request merged**
