### PR TITLE
Support tel: protocol

### PR DESCRIPTION
**Pull request by marapper**
skip links with tel: protocol by default too

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Thank you so much for this PR!  After playing whack-a-mole for months with varying protocol handlers, I think we need to take this a step further and do #104.  If you want to take a shot at that ... great!  Otherwise, I'm going to look at fixing this in a more all-up way.

**Comment by marapper** [comment]
It sounds pretty reasonable. Actually I had some more PRs (if you don't mind of course) for the start. But if I have some time I'll try to help.

**Comment by marapper** [comment]
Especially we have some issues with gaxious. It is not supported HTTP/2 and Youtube have no supported HEAD request for HTTP/1 with 404 code :(

**Comment by marapper** [comment]
Simpliest and accurate way to do #104 is https://github.com/sindresorhus/is-url-superb (to filter out non-urls strings) I think, plus check `!url.match(startsWithProtocol) || url.match(allowedProtocolsPattern)`. How'd u think?

**Comment by JustinBeckwith** [comment]
I knew this was going to be a little involved, and I wanted to set up the code for a few future features so I went ahead and just did this one.  I really do appreciate the PR to start the discussion!  Fix is in #111.

**Pull request closed without merging**
